# 配置文件示例
title = 'example config'
db_driver = 'oracle' # oracle or mssql

[log]

debug = false
file_name = 'jiandaoyun_push_tool.log'

[database]
    [database.oracle]
    host = "127.0.0.1"
    port = 1521
    database_name = "TESTDB"
    username = "SYSTEM"
    password = "P@ssw0rd"

    ld_library_path = 'D:\Oracle\client\12_2'
    nls_lang = 'SIMPLIFIED CHINESE_CHINA.UTF8'

    [database.mssql]
    host = "127.0.0.1"
    port = "1433"
    username = "sa"
    password = "P@ssw0rd"
    database_name = 'queue_demo'

[queue]
    [queue.oracle]
        name = "jdy_push_msg_q"
        message_type = "jdy_push_msg"

    [queue.mssql]
        name = "JDYPushQueue"
        message_type = "JDYPushMessage"
        service = "JDYPushService"
        contract = "JDYPushMessageContract"

[jian_dao_yun]
api_key = "jian_dao_yun_api_key"

    [jian_dao_yun.data_safe_limit]
    # 1-10
    create = 10
    update = 10
    delete = 10

[sync]
departments_table = 'JDY_SYNC_DEPARTMENTS'
users_table = 'JDY_SYNC_USERS'
relationship_table = 'JDY_SYNC_USERS_DEPTS'

[wechat]
corp_id = "wechat_corp_id"
agent_id = 999999
agent_secret = "wechat_agent_secret"
# 接收推送的部门 id
party_id = 999